baseURL = "https://www.sitecorethings.com/"
languageCode = "en-us"
title = "Sitecore Things"
theme = "hucore"
copyright = "&copy; <a href=\"https://github.com/bmyers\">Ben Myers</a> 2017"
googleAnalytics = "UA-58826010-2"
disqusShortname = "sitecore-things"
enableRobotsTXT = true

[taxonomies]
tag = "tags"
category = "categories"

[params]
title = "Sitecore Things"
description = "Sitecore blog braindump of cool things and issue resolution. A place to share findings and for me to remember how I've done things."
keywords = ["Sitecore", "MVC"]
author = "Ben Myers"
sharingicons = true


[params.highlight]
style = "github"
languages = ["cs"]

[[params.social]]
url = "https://github.com/bmyers"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/ben_myers"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
